[package]
name = "hypr-pip-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprland = { git = "https://github.com/PaytonWebber/hyprland-rs", branch = "Fix/windowrulev2" }
tokio = { version = "1.40.0", features = ["full"] }
